### ISSUE TITLE
Compra de componentes restantes

### ISSUE THREAD

**Issue by FlorGrosso** [FlorGrosso/Tesis_EEG#1]
- 2 Capacitores smd tantalio 100u/16V 0805/1206
- 2 Capacitores smd tantalio 10u/ 16V 0805/1206

**Comment by FlorGrosso** [comment]
@yagui no conseguimos estos dos capacitores smd por ningún lado (consultamos a los minoristas de Paraná y a gm), es lo que nos queda para cerrar el diseño. Sabes de algún otro lugar donde podamos conseguir? Si no, de última, ponemos componentes through hole para no dilatar tanto la fabricación de la placa.

**Comment by yagui** [comment]
www.cdronline.com.ar
syc (figuran en el listado aunque quizas no tienen stock)
elemon.com.ar (hay un mínimo no recuerdo cuánto es)
electrocomponentes.com.ar
http://www.arrowar.com/iweb/
intek
