### ISSUE TITLE
Ajustar el diseño.

### ISSUE THREAD

**Issue by FlorGrosso** [FlorGrosso/Tesis_EEG#2]

**Comment by FlorGrosso** [comment]
- Todo listo, Brian imprime el diseño y luego (con los componentes comprados) probamos sobre el esquemático.

**Comment by BrianSantillan** [comment]
- Agregar puntos de referencia X,Y.
- Agregar puntos de fijación del PCB.

**Comment by FlorGrosso** [comment]
![pcb1](https://cloud.githubusercontent.com/assets/13956234/26758949/0ff48e8a-48c5-11e7-82b2-3ed4dac7b3db.jpg)

**Comment by FlorGrosso** [comment]
Otra imagen: 
![pcb2](https://cloud.githubusercontent.com/assets/13956234/26758956/3d621572-48c5-11e7-8933-07adfd24604b.jpeg)
