### ISSUE TITLE
Averiguar posibles fabricantes de placas en caso de que el LCI no tome el diseño.

### ISSUE THREAD

**Issue by FlorGrosso** [FlorGrosso/Tesis_EEG#3]
El grosor de las pistas que vienen o van al ADC y la separación entre ellas es inferior a lo aceptado por el LCI. Hay que ver si nos toman el diseño así o si hay que buscar un lugar donde lo acepten.

**Comment by yagui** [comment]
si quieren pidan presupuestos y sobre todo tiempos de entrega aca
https://www.seeedstudio.com/fusion.html (china considerar costo y tiempo de envío)
http://www.solydes.com/pcb.htm
http://cadipel.com.ar/
http://mayerpcb.com/
http://www.dai-ichi.com.ar/

**Comment by FlorGrosso** [comment]
Muchas gracias Ariel! Vamos a preguntar

**Comment by BrianSantillan** [comment]
Enviado. Espero respuesta de los presupuestos.
