### ISSUE TITLE
Presupuestos PCB

### ISSUE THREAD

**Issue by BrianSantillan** [FlorGrosso/Tesis_EEG#5]
CADIPEL
2 Placas - 4 Semanas - $2500

DAI ICHI
3 Placas - 15 días - U$S120 ($1920)

JCV
2 Placas - 10 días - $2900

Exemso
2 Placas - 10 días - $2092 (posible 5% de descuento)

Ernesto Mayer
...

**Comment by FlorGrosso** [comment]
@yagui, tenes idea si los laboratorios de fiuba mandan placas a hacer a algún lugar particular? el de embebidos, por ejemplo? Quizás ahí conseguimos un mejor precio.

**Comment by yagui** [comment]
no, no se con quien trabaja el laboratorio de embebidos.
Si fuera yo, antes de hacerla yo, la enviaría al LCI. Ahí tienen la luz ultravioleta y la cuba electrolítica.
